### PR TITLE
Fix typo and make license name URL to the LICENSE

### PR DESCRIPTION
**Pull request by agarwalrounak**
Disclamer --> Disclaimer
AGPLv3 --> [AGPLv3](./LICENSE)

### CODE REVIEW

**Comment by agarwalrounak** [comment]
Hi @bzz ! Could you please have a look at my PR?

**Comment by bzz** [comment]
@agarwalrounak - SGTM!

@src-d/applications this repo seems to be missing a MAINTAINER file.

**Comment by smacker** [comment]
@bzz I don't have access to merge or push or whatever here.

**Comment by smacker** [comment]
permissions fixed

**Pull request merged**
